### ISSUE TITLE
calculating ccp

### ISSUE THREAD

**Issue by ajshephard** [tlarroucau/Technology_Health#8]
When calculation the ccp's:
- You should do a location shift to prevent overflow. i.e. also subtract `max(Pi)` from all profit flows before calculating `exp / sumexp`.
- These should have a scale parameter `s>0` which can be set (i.e. calculate `exp(Pi/s)`)

**Comment by tlarroucau** [comment]
Done. I took a scale parameter = 1 for the moment. 
`s_ccp = 1`
I am no longer working in the Dropbox folder now.
